name: README update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' 

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: npm install

      - name: Run the README update script
        run: |
          node index.js
          echo "Script execution completed successfully"

      - name: Auto commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: README automad update
          commit_options: '-a -q'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


          